# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS11Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOS11Demo

  pod 'MJRefresh'


  target 'iOS11DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS11DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
